In [32]:
import numpy as np
import math

In [9]:
n = int(input("Total no.of variables : "))
p = int(input("no.of Independent variables : "))
x = list(map(float, input("Enter x rowwise: ").split()))
# 2.95 6.63 2.53 7.79 3.57 5.65 3.16 5.47 2.58 4.46 2.16 6.22 3.27 3.52
x = np.matrix(x).reshape(n,p)
print("Enter 1 to true and 2 to false")
y = list(map(int, input("Enter y rowwise: ").split()))
y = np.matrix(y).reshape(n,1)
Mu = np.zeros((1, p)) #1:2
for i in range(n):
    Mu = Mu+x[i]
Mu = Mu/n

Total no.of variables : 7
no.of Independent variables : 2
Enter x rowwise: 2.95 6.63 2.53 7.79 3.57 5.65 3.16 5.47 2.58 4.46 2.16 6.22 3.27 3.52
Enter 1 to true and 2 to false
Enter y rowwise: 1 1 1 1 2 2 2


In [12]:
print("x=",x)
print("y=",y)
print("Mu=",Mu)

x= [[2.95 6.63]
 [2.53 7.79]
 [3.57 5.65]
 [3.16 5.47]
 [2.58 4.46]
 [2.16 6.22]
 [3.27 3.52]]
y= [[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]
Mu= [[2.88857143 5.67714286]]


In [18]:
a = list(y).count(1)
b = list(y).count(2)
x1 = np.zeros((a, p))
x2 = np.zeros((b, p))
Mu1 = np.zeros((1, p))
Mu2 = np.zeros((1, p))
for i in range(n):
    if i<a:
        x1[i] = x[i]
        Mu1 = Mu1+x1[i]
    else:
        x2[i-a] = x[i]
        Mu2 = Mu2+x2[i-a]
        
Mu1 = Mu1/a
Mu2 = Mu2/b
print("x1=",x1)
print("Mu1=",Mu1)
print("x2=",x2)
print("Mu2=",Mu2)

x1= [[2.95 6.63]
 [2.53 7.79]
 [3.57 5.65]
 [3.16 5.47]]
Mu1= [[3.0525 6.385 ]]
x2= [[2.58 4.46]
 [2.16 6.22]
 [3.27 3.52]]
Mu2= [[2.67       4.73333333]]


In [19]:
x_Mu = np.zeros((n,p))
for i in range(n):
    x_Mu[i] = x[i]-Mu
    
print(x_Mu)

[[ 0.06142857  0.95285714]
 [-0.35857143  2.11285714]
 [ 0.68142857 -0.02714286]
 [ 0.27142857 -0.20714286]
 [-0.30857143 -1.21714286]
 [-0.72857143  0.54285714]
 [ 0.38142857 -2.15714286]]


In [22]:
def transpose(m):
    ans = list()
    for i in range(len(m[0])):
        a=[]
        for j in range(len(m)):
            a.append(m[j][i])
        ans.append(a)
    return(np.matrix(ans))

In [23]:
C = (transpose(x_Mu)*x_Mu)/n
print(C)

[[ 0.20598367 -0.23093265]
 [-0.23093265  1.69216327]]


In [28]:
def invert_matrix(M):
    n = M.shape[0]
    I = np.identity(n=n)
    M = np.concatenate((M, I), axis=1)
    M = np.concatenate((M[np.any(M != 0, axis=1)], M[np.all(M == 0, axis=1)]), axis=0)
    for i in range(0, n):
        j = 1
        pivot = M[i][i]
        while pivot == 0 and i + j < n:
            M[[i, i + j]] = M[[i + j, i]]
            j += 1
            pivot = M[i][i]
        if pivot == 0:
            return M[:, n:]
        row = M[i]
        M[i] = row / pivot
        for j in [k for k in range(0, n) if k != i]:
            M[j] = M[j] - M[i] * M[j][i]
    return M[:, n:]

In [30]:
C_1 = invert_matrix(np.array(C))
print(C_1)

[[5.73171449 0.78221769]
 [0.78221769 0.69771022]]


In [41]:
print("Enter xk")
xTk = list(map(float, input("Enter xTk rowwise: ").split()))
xTk = np.matrix(xk).reshape(p,1)
print(xTk)

Enter xk
Enter xTk rowwise: 2.81 5.46
[[2.81]
 [5.46]]


In [42]:
# for f1

In [43]:
a1 = Mu1*C_1*xTk
a2 = (0.5)*Mu1*C_1*(transpose(Mu1))
a3 = math.log(a/n)
f1 = a1-a2+a3
print(f1)

[[43.82818099]]


In [44]:
# for f2

In [45]:
b1 = Mu2*C_1*xTk
b2 = (0.5)*Mu2*C_1*(transpose(Mu2))
b3 = math.log(b/n)
f2 = b1-b2+b3
print(f2)

[[43.86302018]]


In [47]:
if f1>f2:
    print("Given condition is true.")
else:
    print("Given condition is false.")

Given condition is false.
