In [24]:
import numpy as np
from scipy import linalg

In [25]:
n=int(input())
p=int(input())
y=list(map(int, input().split()))
# 100 110 105 94 95 99 104 108 105 98 105 110
y=np.matrix(y).reshape(n,1)
x=list(map(int, input("Enter rowwise: ").split()))
# 1 9 62 1 8 58 1 7 64 1 14 60 1 12 63 1 10 57 1 7 55 1 4 56 1 6 59 1 5 61 1 7 57 1 6 60
x=np.matrix(x).reshape(n,p)
xt=x.T

12
3
100 110 105 94 95 99 104 108 105 98 105 110
Enter rowwise: 1 9 62 1 8 58 1 7 64 1 14 60 1 12 63 1 10 57 1 7 55 1 4 56 1 6 59 1 5 61 1 7 57 1 6 60


In [26]:
print("y=",y)
print("x=",x)
print("xt=",xt)

y= [[100]
 [110]
 [105]
 [ 94]
 [ 95]
 [ 99]
 [104]
 [108]
 [105]
 [ 98]
 [105]
 [110]]
x= [[ 1  9 62]
 [ 1  8 58]
 [ 1  7 64]
 [ 1 14 60]
 [ 1 12 63]
 [ 1 10 57]
 [ 1  7 55]
 [ 1  4 56]
 [ 1  6 59]
 [ 1  5 61]
 [ 1  7 57]
 [ 1  6 60]]
xt= [[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 9  8  7 14 12 10  7  4  6  5  7  6]
 [62 58 64 60 63 57 55 56 59 61 57 60]]


In [27]:
xtx_1=linalg.inv(np.dot(xt,x))
xty=np.dot(xt,y)
print(xtx_1)
print(xty)

[[ 4.08944026e+01  1.14046520e-01 -7.03043891e-01]
 [ 1.14046520e-01  1.17514524e-02 -3.49009300e-03]
 [-7.03043891e-01 -3.49009300e-03  1.23147269e-02]]
[[ 1233]
 [ 9636]
 [73094]]


In [28]:
B=np.dot(xtx_1,xty)
B

matrix([[133.46048243],
        [ -1.24850346],
        [ -0.35100837]])

In [29]:
if len(B)==2:
    print("y=",float(B[0]),"+ x",float(B[1]))
elif len(B)==3:
    print("y=",float(B[0]),"+ x1",float(B[1]),"+ x2",float(B[2]))

y= 133.460482428044 + x1 -1.2485034569591869 + x2 -0.3510083718053672


In [30]:
#goodness of fit R2

In [31]:
fy=[]
for i in range(n):
    fy.append(float(B[0]) + float(B[1])*x[i,1] + float(B[2])*x[i,2])
    
fy=list(fy)
fy=np.matrix(fy).reshape(n,1)
print(fy)

[[100.46143226]
 [103.11396921]
 [102.25642243]
 [ 94.92093172]
 [ 96.36491352]
 [100.96797067]
 [105.41549778]
 [108.80999978]
 [105.25996775]
 [105.80645446]
 [104.71348104]
 [104.90895938]]


In [32]:
Eo=y-fy
Eo

matrix([[-0.46143226],
        [ 6.88603079],
        [ 2.74357757],
        [-0.92093172],
        [-1.36491352],
        [-1.96797067],
        [-1.41549778],
        [-0.80999978],
        [-0.25996775],
        [-7.80645446],
        [ 0.28651896],
        [ 5.09104062]])

In [33]:
y_=sum(y)/n
sse=sum(list(np.array(Eo)**2))
sst=0
for i in range(n):
    sst=sst+(y[i]-y_)**2

ssr=sst-sse
R2=ssr/sst

print(y_,sse,sst,R2)

[[102.75]] [151.41040622] [[330.25]] [[0.54152791]]


In [34]:
if R2>0.9:
    print("we accept the model")
else:
    print("we reject the model")

we reject the model


In [35]:
#goodness of fit using ANOVA

In [39]:
alp=0.05
Mssr=ssr/(p-1)
Msse=sse/(n-p)
F=Mssr/Msse
cou=0
if F<1:
    cou=1
    F=1/F
print(F)
import scipy.stats as s
if cou==1:
    Ft=s.f.ppf(1-alp,n-p,p-1)
else:
    Ft=s.f.ppf(1-alp,p-1,n-p)
if F>Ft:
    print("We reject Ho")
    print("There is atleast one Bj that contributes to the table")
    print("We accept the model")
else:
    print("We accept Ho")
    print("There is no Bj that contributes to the table")
    print("We accept the model")

[[5.31521044]]
We reject Ho
There is atleast one Bj that contributes to the table
We accept the model


In [40]:
#to know which variable is more contributing

In [41]:
#Msse , xtx_1
SE=[]
tcal=[]
for i in range(len(B)):
    SE.append((Msse*(xtx_1[i,i]))**0.5)
    tcal.append(B[i]/SE[i])
print(SE)
print(tcal)

[array([26.22941121]), array([0.4446337]), array([0.45516515])]
[matrix([[5.08819971]]), matrix([[-2.80793706]]), matrix([[-0.77116707]])]


In [42]:
import scipy.stats
t=scipy.stats.t.ppf(1-alp/2,n-p)
print(t.round(2))

2.26


In [43]:
for i in range(len(B)):
    if abs(tcal[i])>=t:
        print("We reject Ho")
        print("B"+str(i)+"is contibuting to the model")
    else:
        print("We accept Ho")
        print("B"+str(i)+"is not contibuting to the model")

We reject Ho
B0is contibuting to the model
We reject Ho
B1is contibuting to the model
We accept Ho
B2is not contibuting to the model
